language: python

python:
    - 2.7
    - 3.5
    - 3.6
    - 3.7
    - 3.8
    - 3.9-dev
    - pypy
    - pypy3

install:
    - pip install --upgrade cython
    - pip install --upgrade .

script:
    - cd tests && python trial.py

notifications:
    email: false
